### ISSUE TITLE
Error：Could not create cudnn handle

### ISSUE THREAD

**Issue by SparKgod1** [StoneT2000/rfcl#2]
When using the RFCL training command in ManiSkill, I encountered the following error. Is this due to insufficient GPU memory? According to the instructions, this training should be running on the CPU. Why is this issue occurring? I hope you can provide me some help.

command：

          env_id=DEX_YCB-v1
          demos=20 # number of demos to train on
          seed=42
          XLA_PYTHON_CLIENT_PREALLOCATE=false python ../rfcl_jax/train.py /home/lvxuan/project/dexycb/baseline/ManiSkill/examples/baselines/rfcl/configs/base_sac_ms3.yml \
          logger.exp_name="ms3/${env_id}/rfcl_${demos}_demos_s${seed}" logger.wandb=True \
          seed=${seed} train.num_demos=${demos} train.steps=1_000_000 \
          env.env_id=${env_id} \
          train.dataset_path="/home/lvxuan/project/dexycb/baseline/lx/traj_data/trajectory_left.state.pd_joint_delta_pos.h5"

Error：

        /home/lvxuan/miniconda3/envs/rfcl/bin/python /home/lvxuan/project/dexycb/baseline/lx/train.py 
        /home/lvxuan/project/dexycb/baseline/lx/../rfcl_jax/train.py:125: UserWarning: exps/ms3/DEX_YCB-v1/rfcl_20_demos_s42_5 already exists. Changing exp_name to ms3/DEX_YCB-v1/rfcl_20_demos_s42_6
          warnings.warn(f"{prev_exp_path} already exists. Changing exp_name to {cfg.logger.exp_name}")
        Converted /home/lvxuan/project/dexycb/baseline/lx/traj_data/trajectory_left.state.pd_joint_delta_pos.h5, skip_failed=True, shuffle=True, loaded 11 demos
        Loaded 11 demos, total 1430 frames. Loaded [5, 0, 9, 10, 2, 1, 8, 4, 7, 3, 6]
        /home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/gymnasium/core.py:311: UserWarning: WARN: env.max_episode_steps to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.max_episode_steps` for environment variables or `env.get_wrapper_attr('max_episode_steps')` that will search the reminding wrappers.
          logger.warn(
        /home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/gymnasium/core.py:311: UserWarning: WARN: env.max_episode_steps to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.max_episode_steps` for environment variables or `env.get_wrapper_attr('max_episode_steps')` that will search the reminding wrappers.
          logger.warn(
        E0725 17:14:49.392478  104725 cuda_dnn.cc:535] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
        E0725 17:14:49.392518  104725 cuda_dnn.cc:539] Memory usage: 4069916672 bytes free, 6200492032 bytes total.
        E0725 17:14:49.392762  104725 cuda_dnn.cc:535] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
        E0725 17:14:49.392776  104725 cuda_dnn.cc:539] Memory usage: 4069916672 bytes free, 6200492032 bytes total.
        Traceback (most recent call last):
          File "/home/lvxuan/project/dexycb/baseline/lx/../rfcl_jax/train.py", line 374, in <module>
            main(cfg)
          File "/home/lvxuan/project/dexycb/baseline/lx/../rfcl_jax/train.py", line 226, in main
            ac = create_ac_model()
          File "/home/lvxuan/project/dexycb/baseline/lx/../rfcl_jax/train.py", line 214, in create_ac_model
            jax.random.PRNGKey(cfg.seed),
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/random.py", line 233, in PRNGKey
            return _return_prng_keys(True, _key('PRNGKey', seed, impl))
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/random.py", line 195, in _key
            return prng.random_seed(seed, impl=impl)
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/prng.py", line 533, in random_seed
            seeds_arr = jnp.asarray(np.int64(seeds))
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 3289, in asarray
            return array(a, dtype=dtype, copy=bool(copy), order=order)
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 3214, in array
            out_array: Array = lax_internal._convert_element_type(
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 559, in _convert_element_type
            return convert_element_type_p.bind(operand, new_dtype=new_dtype,
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/core.py", line 416, in bind
            return self.bind_with_trace(find_top_trace(args), args, params)
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/core.py", line 420, in bind_with_trace
            out = trace.process_primitive(self, map(trace.full_raise, args), params)
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/core.py", line 921, in process_primitive
            return primitive.impl(*tracers, **params)
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/dispatch.py", line 87, in apply_primitive
            outs = fun(*args)
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 179, in reraise_with_filtered_traceback
            return fun(*args, **kwargs)
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/pjit.py", line 327, in cache_miss
            outs, out_flat, out_tree, args_flat, jaxpr, attrs_tracked = _python_pjit_helper(
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/pjit.py", line 185, in _python_pjit_helper
            out_flat = pjit_p.bind(*args_flat, **params)
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/core.py", line 2834, in bind
            return self.bind_with_trace(top_trace, args, params)
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/core.py", line 420, in bind_with_trace
            out = trace.process_primitive(self, map(trace.full_raise, args), params)
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/core.py", line 921, in process_primitive
            return primitive.impl(*tracers, **params)
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/pjit.py", line 1635, in _pjit_call_impl
            return xc._xla.pjit(
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/pjit.py", line 1614, in call_impl_cache_miss
            out_flat, compiled = _pjit_call_impl_python(
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/pjit.py", line 1536, in _pjit_call_impl_python
            compiled = _resolve_and_lower(
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/interpreters/pxla.py", line 2496, in compile
            executable = UnloadedMeshExecutable.from_hlo(
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/interpreters/pxla.py", line 2995, in from_hlo
            xla_executable = _cached_compilation(
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/interpreters/pxla.py", line 2810, in _cached_compilation
            xla_executable = compiler.compile_or_get_cached(
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/compiler.py", line 378, in compile_or_get_cached
            return _compile_and_write_cache(
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/compiler.py", line 608, in _compile_and_write_cache
            executable = backend_compile(
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/profiler.py", line 335, in wrapper
            return func(*args, **kwargs)
          File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/compiler.py", line 238, in backend_compile
            return backend.compile(built_c, compile_options=options)
        jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.

**Comment by StoneT2000** [comment]
what version of jax and torch are you using? And are you using the ms3 branch of code (the one maniskill3 repo git clones for baseline)

and for a sanity check can you try in a new python file running

import jax
import torch
print(jax.numpy.array([1.5,2.0]).mean())

**Comment by SparKgod1** [comment]
@StoneT2000 Oh, it seems I can't run this either and I’m encountering the same error. I installed rfcl_jax following the instructions [here](https://github.com/haosulab/ManiSkill/tree/main/examples/baselines/rfcl#installation) in ManiSkill, and I am using the ms3-gpu branch. My PyTorch version is 2.3.1. How can I solve this? Thank you so much for your help.

**Comment by StoneT2000** [comment]
what version of jax?

**Comment by SparKgod1** [comment]
> what version of jax?

0.4.13

**Comment by StoneT2000** [comment]
Can you install 0.4.28 instead and then run again?

**Comment by SparKgod1** [comment]
> Can you install 0.4.28 instead and then run again?

when I use jax==0.4.28,error occurs as below:

      Traceback (most recent call last):
        File "/home/lvxuan/project/dexycb/baseline/lx/../rfcl_jax/train.py", line 15, in <module>
          import jax
        File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/__init__.py", line 37, in <module>
          import jax.core as _core
        File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/core.py", line 18, in <module>
          from jax._src.core import (
        File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/core.py", line 39, in <module>
          from jax._src import dtypes
        File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/dtypes.py", line 33, in <module>
          from jax._src import config
        File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/config.py", line 27, in <module>
          from jax._src import lib
        File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 75, in <module>
          version = check_jaxlib_version(
        File "/home/lvxuan/miniconda3/envs/rfcl/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 67, in check_jaxlib_version
          raise RuntimeError(
      RuntimeError: jaxlib version 0.4.30 is newer than and incompatible with jax version 0.4.28. Please update your jax and/or jaxlib packages.

but then I use jax==0.4.30, the same error occurs as I encountered first.If it's all because the version of jax?

**Comment by SparKgod1** [comment]
Thanks for the reply. I fixed it through pip install `jax[cuda12_pip]`， but it's not completely resolved because the installed version of cuDNN is incompatible with the PyTorch version.

The error is as follows:
    
    torch 2.3.1 requires nvidia-cudnn-cu12==8.9.2.26; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 9.2.1.18 which is incompatible.

However, it can still run normally.Thanks again for your advice.

**Comment by StoneT2000** [comment]
I recommend following the installation instructions again, I have updated them. The warning/error you got might be problematic.
